name = "options-calculator"
type = "javascript"
compatibility_date = "2024-12-18"

pages_build_output_dir = "public"

routes = [
  { pattern = "options.shanehull.dev/*", zone_name = "shanehull.dev" },
  { pattern = "www.options.shanehull.dev/*", zone_name = "shanehull.dev" }
]

[env.production]
name = "options-calculator-prod"
routes = [
  { pattern = "options.shanehull.dev/*", zone_name = "shanehull.dev" },
  { pattern = "www.options.shanehull.dev/*", zone_name = "shanehull.dev" }
]

[env.staging]
name = "options-calculator-staging"
